// Import Anchor's prelude — all the essential types and macros
use anchor_lang::prelude::*;
// Import the System Program's transfer helper and Transfer struct
// These let us call the System Program to move SOL
use anchor_lang::system_program::{transfer, Transfer};

// Declare your program's on-chain address
// This MUST match the program ID in Anchor.toml
// This ID was generated by anchor init and is unique to your program
// Keep YOUR generated ID, not the one from the lesson
declare_id!("Fx9Aiecv9fA7jCgN4PKWEVDT9rXAnh2pbePPGSGRmneU");

// ==========================================================
// INSTRUCTION HANDLERS
// ==========================================================

#[program]
pub mod sol_mover {
    use super::*;

    // ==========================================================
    // INSTRUCTION: sol_transfer
    // ==========================================================
    // WHAT: Moves SOL from sender to recipient using a CPI to the System Program
    // WHO: The sender must sign the transaction (real wallet, not PDA)
    // HOW: Calls the System Program's transfer instruction via CPI
    // WHY: Only the System Program can reduce lamports from a wallet
    // RETURNS: Ok(()) on success, error if transfer fails
    // ==========================================================
    pub fn sol_transfer(ctx: Context<SolTransfer>, amount: u64) -> Result<()> {
        // Step 1: Build the accounts struct for the System Program's transfer
        // The System Program's transfer instruction expects:
        //   - from: the account sending SOL (must be mutable)
        //   - to: the account receiving SOL (must be mutable)
        // to_account_info() converts our Anchor accounts to the generic AccountInfo type
        // that the System Program expects for CPI calls
        let cpi_accounts = Transfer {
            from: ctx.accounts.sender.to_account_info(),
            to: ctx.accounts.recipient.to_account_info(),
        };

        // Step 2: Build the CPI context
        // CpiContext bundles the program we're calling and the accounts it needs
        // ctx.accounts.system_program.key() is the System Program's public key
        // The .key() returns a Pubkey, which Anchor 1.0 expects as the first argument
        // (Older Anchor versions expected an AccountInfo here, hence the warning)
        let cpi_context = CpiContext::new(
            ctx.accounts.system_program.key(),
            cpi_accounts,
        );

        // Step 3: Fire the cross-program invocation
        // transfer() is the System Program's transfer instruction
        // It takes the CPI context and the amount in lamports
        // The ? operator returns any error from the CPI
        // If the transfer fails, the entire transaction rolls back
        transfer(cpi_context, amount)?;

        Ok(())
    }
}

// ==========================================================
// ACCOUNT VALIDATION STRUCTS
// ==========================================================

// ==========================================================
// ACCOUNTS FOR: sol_transfer
// ==========================================================
// WHAT: Defines the accounts needed to transfer SOL
// ACCOUNTS:
//   sender: The wallet sending SOL (must sign, balance decreases)
//   recipient: The wallet receiving SOL (balance increases)
//   system_program: The System Program (required for CPI)
// CONSTRAINTS:
//   mut: Both sender and recipient balances change
//   Signer: sender must sign the transaction
//   SystemAccount: recipient is a system-owned account (standard wallet)
// ==========================================================
#[derive(Accounts)]
pub struct SolTransfer<'info> {
    // The wallet sending SOL
    // mut: its lamport balance will decrease
    // Signer: this account must sign the outer transaction
    // The signature is forwarded to the System Program via CPI
    #[account(mut)]
    pub sender: Signer<'info>,

    // The wallet receiving SOL
    // mut: its lamport balance will increase
    // SystemAccount: a wallet owned by the System Program
    #[account(mut)]
    pub recipient: SystemAccount<'info>,

    // The System Program's public key
    // Required because we're calling the System Program via CPI
    // Anchor will fill this automatically if you omit it from the test
    pub system_program: Program<'info, System>,
}