// Import Anchor's prelude — all the essential types and macros
use anchor_lang::prelude::*;

// Declare your program's on-chain address
// This MUST match the program ID in Anchor.toml and target/deploy/counter-keypair.json
// This ID was generated by anchor init and is unique to your program
declare_id!("DJDzMCambWr4MYuxTTh4TJRq839c2RpNxrAemHDppz1g");

// ==========================================================
// INSTRUCTION HANDLERS
// ==========================================================

#[program]
pub mod counter {
    use super::*;



    // ==========================================================
    // INSTRUCTION: init_counter
    // WHAT: Creates a new counter account for a specific user
    // ==========================================================
    // WHO: Any user who doesn't already have a counter
    // HOW: Derives the account address from "counter" + user's pubkey
    // WHAT HAPPENS: Creates a Counter account at the PDA with count = 0
    // RETURNS: Ok(()) on success
    // ==========================================================
    pub fn init_counter(ctx: Context<InitCounter>) -> Result<()> {
        // Get a mutable reference to the Counter account
        let counter = &mut ctx.accounts.counter;
        
        // Store the user's public key in the account
        // This is the wallet that owns this counter
        counter.user = ctx.accounts.user.key();
        
        // Initialize the count to zero
        counter.count = 0;
        
        // Store the bump seed used to derive this PDA
        // This is needed to re-derive the same address in the increment instruction
        // ctx.bumps contains all bump seeds for PDA accounts in this instruction
        counter.bump = ctx.bumps.counter;

        let config = &mut ctx.accounts.config;
        config.total_counters = config.total_counters.checked_add(1).unwrap();
        
        Ok(())
    }

    // ==========================================================
    // INSTRUCTION: increment
    // ==========================================================
    // WHAT: Increases the counter by 1 for the calling user
    // WHO: Only the user who owns the counter
    // HOW: Seeds constraint ensures the PDA matches the user
    // WHAT HAPPENS: counter.count += 1
    // RETURNS: Ok(()) on success, Overflow error if count exceeds u64 max
    // ==========================================================
    pub fn increment(ctx: Context<Increment>) -> Result<()> {
        // Get a mutable reference to the Counter account
        let counter = &mut ctx.accounts.counter;
        
        // Add 1 to the count, checking for overflow
        // checked_add returns None if count would exceed u64 max
        counter.count = counter
            .count
            .checked_add(1)
            .ok_or(CounterError::Overflow)?;
            
        Ok(())
    }

    // ==========================================================
    // INSTRUCTION: init_config
    // ==========================================================
    // WHAT: Creates the global Config account (singleton)
    // WHO: The first wallet that calls this becomes the admin
    // HOW: Derives the account address from "config" seed
    // WHAT HAPPENS: Creates a Config PDA with admin = signer, paused = false, total_counters = 0
    // RETURNS: Ok(()) on success
    // ==========================================================
    pub fn init_config(ctx: Context<InitConfig>) -> Result<()> {
        let config = &mut ctx.accounts.config;
        config.admin = ctx.accounts.admin.key();
        config.paused = false;
        config.total_counters = 0;
        config.bump = ctx.bumps.config;
        Ok(())
    }


    // ==========================================================
    // INSTRUCTION: set_paused
    // ==========================================================
    // WHAT: Toggles the paused state of the program
    // WHO: Only the admin (set in init_config)
    // WHAT HAPPENS: config.paused = paused
    // RETURNS: Ok(()) on success
    // ==========================================================
    pub fn set_paused(ctx: Context<SetPaused>, paused: bool) -> Result<()> {
        ctx.accounts.config.paused = paused;
        Ok(())
    }

    // ==========================================================
    // INSTRUCTION: close_counter
    // ==========================================================
    // WHAT: Closes a counter account and refunds the rent
    // WHO: Only the user who owns the counter
    // HOW: close = user attribute transfers lamports to user
    // WHAT HAPPENS: Account is closed, lamports returned to user
    // RETURNS: Ok(()) on success
    // ==========================================================
    pub fn close_counter(_ctx: Context<CloseCounter>) -> Result<()> {
        Ok(())
    }
}

// ==========================================================
// ACCOUNT VALIDATION STRUCTS
// ==========================================================

// ==========================================================
// ACCOUNTS FOR: init_config
// ==========================================================
// WHAT: Defines the accounts needed to create the Config PDA
// ACCOUNTS:
//   config: The Config account to create (PDA derived from "config" seed)
//   admin: The wallet that will become the admin (pays rent, signs)
//   system_program: Required for creating accounts
// CONSTRAINTS:
//   init: Create the account
//   payer = admin: admin pays for rent
//   space = 8 + Config::INIT_SPACE: 8 bytes discriminator + data size
//   seeds = [b"config"]: Singleton — only one Config PDA exists
//   bump: Store the bump in the account automatically
// ==========================================================
#[derive(Accounts)]
pub struct InitConfig<'info> {
    #[account(
        init,
        payer = admin,
        space = 8 + Config::INIT_SPACE,
        seeds = [b"config"],
        bump
    )]
    pub config: Account<'info, Config>,
    #[account(mut)]
    pub admin: Signer<'info>,
    pub system_program: Program<'info, System>,
}

// ==========================================================
// ACCOUNTS FOR: init_counter
// ==========================================================
// WHAT: Defines the accounts needed to create a new counter
// ACCOUNTS:
//   config: The Config PDA (must exist and be mutable)
//   counter: The counter account to create (PDA derived from seeds)
//   user: The wallet that will own the counter (pays rent, signs)
//   system_program: Required for creating accounts
// CONSTRAINTS:
//   config: mut, seeds = [b"config"], bump = config.bump
//   counter::
//   init: Create the account (CPI to System Program)
//   payer = user: user pays for rent
//   space = 8 + Counter::INIT_SPACE: 8 bytes discriminator + data size
//   seeds = [b"counter", user.key().as_ref()]: Derive address from these seeds
//   bump: Store the bump in the account automatically
// ==========================================================
#[derive(Accounts)]
pub struct InitCounter<'info> {
    #[account(
        mut,
        seeds = [b"config"],
        bump = config.bump,
    )]
    pub config: Account<'info, Config>,
    #[account(
        init,                           // Create this account
        payer = user,                   // user pays the rent
        space = 8 + Counter::INIT_SPACE, // 8 bytes discriminator + data size
        seeds = [b"counter", user.key().as_ref()], // Derive PDA from "counter" + user's pubkey
        bump                            // Store the bump in the account
    )]
    pub counter: Account<'info, Counter>,
    #[account(mut)]                     // This account pays lamports (rent)
    pub user: Signer<'info>,            // Must sign the transaction
    pub system_program: Program<'info, System>, // Required for account creation
}

// ==========================================================
// ACCOUNTS FOR: increment
// ==========================================================
// WHAT: Defines the accounts needed to increment a counter
// ACCOUNTS:
//   config: The Config PDA (to check if paused)
//   counter: The counter account to modify (PDA derived from seeds)
//   user: The wallet that must match the counter's user
// CONSTRAINTS:
//   config: seeds = [b"config"], bump = config.bump, constraint = !config.paused
//   counter::
//   mut: The counter data will be modified
//   seeds: seeds = [b"counter", user.key().as_ref()]
//   bump = counter.bump: Use the bump stored in the account
//   has_one = user
// 
// The constraint ensures increments are not paused.
// The has_one ensures only the owner can increment.
// ==========================================================
#[derive(Accounts)]
pub struct Increment<'info> {
    #[account(
        seeds = [b"config"],
        bump = config.bump,
        constraint = !config.paused @ CounterError::Paused,
    )]
    pub config: Account<'info, Config>,
    #[account(
        mut,                            // The counter data will be modified
        seeds = [b"counter", user.key().as_ref()], // Re-derive the PDA
        bump = counter.bump,             // Use the bump stored in the account
        has_one = user,
    )]
    pub counter: Account<'info, Counter>,
    pub user: Signer<'info>,            // Must sign the transaction
}

// ==========================================================
// ACCOUNTS FOR: set_paused
// ==========================================================
// WHAT: Defines the accounts needed to toggle the paused state
// ACCOUNTS:
//   config: The Config PDA (must be mutable)
//   admin: The wallet that must match config.admin
// CONSTRAINTS:
//   config: mut, seeds = [b"config"], bump = config.bump, has_one = admin
// 
// has_one ensures only the admin can change the paused state.
// ==========================================================
#[derive(Accounts)]
pub struct SetPaused<'info> {
    #[account(
        mut,
        seeds = [b"config"],
        bump = config.bump,
        has_one = admin,
    )]
    pub config: Account<'info, Config>,
    pub admin: Signer<'info>,
}

// ==========================================================
// ACCOUNTS FOR: close_counter
// ==========================================================
// WHAT: Defines the accounts needed to close a counter
// ACCOUNTS:
//   counter: The counter account to close (PDA derived from seeds)
//   user: The wallet that must match counter.user (receives rent refund)
// CONSTRAINTS:
//   mut: The counter account will be modified (lamports transferred out)
//   close = user: Drain all lamports from counter into user
//   seeds: Derive address from "counter" + user's pubkey
//   bump = counter.bump: Use the stored bump
//   has_one = user: Only the owner can close their counter
// ==========================================================
#[derive(Accounts)]
pub struct CloseCounter<'info> {
    #[account(
        mut,
        close = user,
        seeds = [b"counter", user.key().as_ref()],
        bump = counter.bump,
        has_one = user,
    )]
    pub counter: Account<'info, Counter>,
    #[account(mut)]
    pub user: Signer<'info>,
}


// This defines what data is stored in every Counter account.
// Each Counter account is stored at a PDA derived from "counter" + user's pubkey.
// 
// The account size is:
//   - 8 bytes: Anchor discriminator (identifies this account type)
//   - 32 bytes: user (Pubkey)
//   - 8 bytes: count (u64)
//   - 1 byte: bump (u8)
//   - Total: 49 bytes
// ==========================================================
#[account]
#[derive(InitSpace)]
pub struct Counter {
    // The wallet that owns this counter (32 bytes)
    // Set once in init_counter, never changes
    pub user: Pubkey,
    
    // The actual counter value (8 bytes)
    // Starts at 0, increases by 1 each increment
    pub count: u64,
    
    // The bump seed used to derive this PDA (1 byte)
    // Stored so increment can re-derive the same address
    pub bump: u8,
}

// The Config account stores global program settings.
// It is a singleton — only one Config PDA exists for the entire program.
// 
// The account size is:
//   - 8 bytes: Anchor discriminator (identifies this account type)
//   - 32 bytes: admin (Pubkey)
//   - 1 byte: paused (bool)
//   - 8 bytes: total_counters (u64)
//   - 1 byte: bump (u8)
//   - Total: 50 bytes
#[account]
#[derive(InitSpace)]
pub struct Config {
    pub admin: Pubkey,          // The wallet that controls the program
    pub paused: bool,           // If true, no increments allowed
    pub total_counters: u64,    // How many counters have been created
    pub bump: u8,               // The bump seed for the Config PDA
}


// ==========================================================
// CUSTOM ERROR CODES
// ==========================================================

#[error_code]
pub enum CounterError {
    #[msg("counter overflow")]
    Overflow,
    #[msg("Increments are currently paused")]
    Paused,
}
