// Import Anchor's core types needed for working with accounts and instructions
use anchor_lang::{
    solana_program::system_program,  // The System Program (required for creating accounts)
    AccountDeserialize,              // Trait for deserializing account data
    InstructionData,                 // Trait for building instruction data
    ToAccountMetas,                  // Trait for converting accounts to account metas
};

// Import from your counter program
// These are automatically generated by Anchor from your lib.rs
use counter::{accounts as counter_accounts, instruction as counter_instruction, Counter};

// LiteSVM = local Solana VM for testing (no devnet required)
use litesvm::LiteSVM;

// Solana types for building transactions
use solana_instruction::Instruction;  // Represents a single instruction
use solana_keypair::Keypair;          // Keypair for signing
use solana_signer::Signer;            // Trait for signers
use solana_transaction::Transaction;  // Represents a transaction

// This is a test function. The #[test] attribute tells Rust to run it during testing.
#[test]
fn initialize_sets_count_to_zero() {
    // 1. Create a new local Solana VM (LiteSVM)
    // This is like a mini blockchain running on your computer
    let mut svm = LiteSVM::new();

    // 2. Create a fake wallet (payer) and give it 10 SOL
    let payer = Keypair::new();  // Generate a new keypair
    // Airdrop 10 SOL to the payer (10 * 1,000,000,000 lamports = 10 SOL)
    svm.airdrop(&payer.pubkey(), 10 * 1_000_000_000).unwrap();

    // 3. Load your compiled program into the VM
    // counter::ID is the program ID from declare_id! in lib.rs
    let program_id = counter::ID;
    // The path to the compiled program file (.so file from anchor build)
    let so_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../target/deploy/counter.so");
    svm.add_program_from_file(program_id, so_path).unwrap();

    // 4. Create a new keypair for the counter account
    // This address will be where the counter data is stored
    let counter_kp = Keypair::new();

    // 5. Build the instruction
    let ix = Instruction {
        program_id,  // Which program to call (your counter program)
        accounts: counter_accounts::Initialize {
            // These are the accounts your initialize instruction expects
            counter: counter_kp.pubkey(),          // The counter account to create
            authority: payer.pubkey(),             // The wallet that will own the counter
            system_program: system_program::ID,    // System Program (required for account creation)
        }
        .to_account_metas(None),  // Convert accounts to the format Solana expects
        data: counter_instruction::Initialize {}.data(),  // The instruction data (empty for initialize)
    };

    // 6. Build and sign the transaction
    let tx = Transaction::new_signed_with_payer(
        &[ix],                     // The instructions to execute
        Some(&payer.pubkey()),     // Who pays for the transaction
        &[&payer, &counter_kp],    // Signers (payer + counter keypair both sign)
        svm.latest_blockhash(),    // Recent blockhash (prevents replay)
    );

    // 7. Send the transaction to the VM
    // This executes your initialize instruction
    svm.send_transaction(tx).expect("initialize should succeed");

    // 8. Fetch the counter account from the VM
    let raw = svm.get_account(&counter_kp.pubkey()).expect("counter exists");

    // 9. Deserialize the raw bytes into a Counter struct
    let state = Counter::try_deserialize(&mut raw.data.as_slice()).unwrap();

    // 10. Assert the state is what we expect
    assert_eq!(state.count, 0);                      // count should be 0
    assert_eq!(state.authority, payer.pubkey());    // authority should be the payer
}