skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "Ex9Jpn1RF4uUP24anLNrP8XPuTcWF9VPpdftqcQ7dRJX"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
