// Import Anchor's prelude — all the essential types and macros
use anchor_lang::prelude::*;

// Declare your program's on-chain address
// This MUST match the program ID in Anchor.toml and target/deploy/counter-keypair.json
// This ID was generated by anchor init and is unique to your program
declare_id!("DJDzMCambWr4MYuxTTh4TJRq839c2RpNxrAemHDppz1g");

// ==========================================================
// INSTRUCTION HANDLERS
// ==========================================================

#[program]
pub mod counter {
    use super::*;

    // ==========================================================
    // INSTRUCTION: init_counter
    // ==========================================================
    // WHAT: Creates a new counter account for a specific user
    // WHO: Any user who doesn't already have a counter
    // HOW: Derives the account address from "counter" + user's pubkey
    // WHAT HAPPENS: Creates a Counter account at the PDA with count = 0
    // RETURNS: Ok(()) on success
    // ==========================================================
    pub fn init_counter(ctx: Context<InitCounter>) -> Result<()> {
        // Get a mutable reference to the Counter account
        let counter = &mut ctx.accounts.counter;
        
        // Store the user's public key in the account
        // This is the wallet that owns this counter
        counter.user = ctx.accounts.user.key();
        
        // Initialize the count to zero
        counter.count = 0;
        
        // Store the bump seed used to derive this PDA
        // This is needed to re-derive the same address in the increment instruction
        // ctx.bumps contains all bump seeds for PDA accounts in this instruction
        counter.bump = ctx.bumps.counter;
        
        Ok(())
    }

    // ==========================================================
    // INSTRUCTION: increment
    // ==========================================================
    // WHAT: Increases the counter by 1 for the calling user
    // WHO: Only the user who owns the counter
    // HOW: Seeds constraint ensures the PDA matches the user
    // WHAT HAPPENS: counter.count += 1
    // RETURNS: Ok(()) on success, Overflow error if count exceeds u64 max
    // ==========================================================
    pub fn increment(ctx: Context<Increment>) -> Result<()> {
        // Get a mutable reference to the Counter account
        let counter = &mut ctx.accounts.counter;
        
        // Add 1 to the count, checking for overflow
        // checked_add returns None if count would exceed u64 max
        counter.count = counter
            .count
            .checked_add(1)
            .ok_or(CounterError::Overflow)?;
            
        Ok(())
    }
}

// ==========================================================
// ACCOUNT VALIDATION STRUCTS
// ==========================================================

// ==========================================================
// ACCOUNTS FOR: init_counter
// ==========================================================
// WHAT: Defines the accounts needed to create a new counter
// ACCOUNTS:
//   counter: The counter account to create (PDA derived from seeds)
//   user: The wallet that will own the counter (pays rent, signs)
//   system_program: Required for creating accounts
// CONSTRAINTS:
//   init: Create the account (CPI to System Program)
//   payer = user: user pays for rent
//   space = 8 + Counter::INIT_SPACE: 8 bytes discriminator + data size
//   seeds = [b"counter", user.key().as_ref()]: Derive address from these seeds
//   bump: Store the bump in the account automatically
// ==========================================================
#[derive(Accounts)]
pub struct InitCounter<'info> {
    #[account(
        init,                           // Create this account
        payer = user,                   // user pays the rent
        space = 8 + Counter::INIT_SPACE, // 8 bytes discriminator + data size
        seeds = [b"counter", user.key().as_ref()], // Derive PDA from "counter" + user's pubkey
        bump                            // Store the bump in the account
    )]
    pub counter: Account<'info, Counter>,
    
    #[account(mut)]                     // This account pays lamports (rent)
    pub user: Signer<'info>,            // Must sign the transaction
    
    pub system_program: Program<'info, System>, // Required for account creation
}

// ==========================================================
// ACCOUNTS FOR: increment
// ==========================================================
// WHAT: Defines the accounts needed to increment a counter
// ACCOUNTS:
//   counter: The counter account to modify (PDA derived from seeds)
//   user: The wallet that must match the counter's user
// CONSTRAINTS:
//   mut: The counter data will be modified
//   seeds: Derive address from "counter" + user's pubkey
//   bump = counter.bump: Use the bump stored in the account
// 
// IMPORTANT: This is how authorization works WITHOUT has_one!
// If a different user tries to increment, the seed derivation produces
// a different address, so Anchor won't find the right account.
// ==========================================================
#[derive(Accounts)]
pub struct Increment<'info> {
    #[account(
        mut,                            // The counter data will be modified
        seeds = [b"counter", user.key().as_ref()], // Re-derive the PDA
        bump = counter.bump,             // Use the bump stored in the account
    )]
    pub counter: Account<'info, Counter>,
    
    pub user: Signer<'info>,            // Must sign the transaction
}

// ==========================================================
// ON-CHAIN DATA STRUCTURE
// ==========================================================
// This defines what data is stored in every Counter account.
// Each Counter account is stored at a PDA derived from "counter" + user's pubkey.
// 
// The account size is:
//   - 8 bytes: Anchor discriminator (identifies this account type)
//   - 32 bytes: user (Pubkey)
//   - 8 bytes: count (u64)
//   - 1 byte: bump (u8)
//   - Total: 49 bytes
// ==========================================================

#[account]
#[derive(InitSpace)]
pub struct Counter {
    // The wallet that owns this counter (32 bytes)
    // Set once in init_counter, never changes
    pub user: Pubkey,
    
    // The actual counter value (8 bytes)
    // Starts at 0, increases by 1 each increment
    pub count: u64,
    
    // The bump seed used to derive this PDA (1 byte)
    // Stored so increment can re-derive the same address
    pub bump: u8,
}

// ==========================================================
// CUSTOM ERROR CODES
// ==========================================================

#[error_code]
pub enum CounterError {
    #[msg("counter overflow")]
    Overflow,
}