skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "75Us8XjhjHDoY6uemCSHt4Qv6S8mo2M2PpPFTi5uDrSN"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
